CREATE DATABASE IF NOT EXISTS testDB;

USE testDB;

CREATE TABLE IF NOT EXISTS testCase (`id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255), `idPlan` INT, descr` VARCHAR(255), `inp` TEXT, `out` TEXT);

CREATE TABLE IF NOT EXISTS testPlan (`id` INT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255) PRIMARY KEY, `descr` VARCHAR(255));